version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: anga_mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true" # Mantenha esta linha
      MYSQL_DATABASE: anga_db
      # REMOVA A LINHA ABAIXO: MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_db_data: